# Generated by Django 3.0.8 on 2020-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(blank=True, max_length=25),
        ),
    ]
